import React, {useMemo, useState} from 'react';
import { createRoot } from 'react-dom/client';
import { AlertTriangle, CalendarDays, CheckCircle2, FileText, Gauge, LayoutDashboard, Search, Sun, UsersRound, ClipboardCheck, Plus, Camera, MapPin, Wrench, ShieldCheck, Clock, Home, Zap } from 'lucide-react';
import logo from './logo-mf.jpg';
import './style.css';

function Status({children}){const c={Resolvido:'green',Normal:'green','Bem-sucedido':'green',Pendente:'red','Com alerta':'red','Em análise':'blue',Agendado:'yellow',Confirmado:'green',Acompanhar:'orange',Alta:'red',Média:'yellow',Coletada:'green'}[children]||'gray';return <span className={`status ${c}`}>{children}</span>}
function Card({title,value,desc,Icon}){return <div className="card"><div className="cardTop"><div><p>{title}</p><h3>{value}</h3></div><div className="icon"><Icon size={26}/></div></div><small>{desc}</small></div>}
function App(){
 const paineis=['SOLARMAN','SOLIS','GOODWE','RENAC','ELEKEEPER','AUXSOL'];
 const [aba,setAba]=useState('dashboard'); const [busca,setBusca]=useState(''); const [filtro,setFiltro]=useState('Todos');
 const alertas=[
 {id:'AL-001',cliente:'Fazenda Oliveira',painel:'SOLARMAN',inversor:'Inversor 01',situacao:'Baixa geração detectada no período da tarde',prioridade:'Alta',responsavel:'Equipe Técnica 01',data:'15/05/2026',horario:'14:18',status:'Pendente',contato:'(91) 90000-0001',obs:'Verificar string 02, conectores e possível sombreamento parcial.'},
 {id:'AL-002',cliente:'Mercado Central',painel:'SOLIS',inversor:'Solis 8kW',situacao:'Falha de comunicação com inversor',prioridade:'Média',responsavel:'Lucas',data:'15/05/2026',horario:'10:45',status:'Resolvido',contato:'(91) 90000-0002',obs:'Comunicação restabelecida após reinicialização e conferência de rede.'},
 {id:'AL-003',cliente:'Residencial Souza',painel:'GOODWE',inversor:'GoodWe 5kW',situacao:'Sistema sem atualização há mais de 24h',prioridade:'Alta',responsavel:'Equipe Técnica 02',data:'14/05/2026',horario:'17:22',status:'Em análise',contato:'(91) 90000-0003',obs:'Cliente informou queda de internet. Aguardar retorno e validar no painel.'},
 {id:'AL-004',cliente:'Comercial Almeida',painel:'RENAC',inversor:'Renac 10kW',situacao:'Oscilação de tensão registrada no histórico',prioridade:'Média',responsavel:'Plantão Monitoramento',data:'13/05/2026',horario:'09:15',status:'Acompanhar',contato:'(91) 90000-0004',obs:'Acompanhar nova ocorrência antes de abrir visita externa.'}];
 const agenda=[{data:'16/05/2026',horario:'08:00',local:'Residencial Souza',endereco:'Bairro Centro',servico:'Verificar comunicação do inversor e rede Wi-Fi',equipe:'Equipe Técnica 02',tipo:'Manutenção corretiva',status:'Agendado',prioridade:'Alta'},{data:'16/05/2026',horario:'14:30',local:'Fazenda Oliveira',endereco:'Zona Rural',servico:'Inspeção em string com baixa geração',equipe:'Equipe Técnica 01',tipo:'Visita técnica',status:'Pendente',prioridade:'Alta'},{data:'17/05/2026',horario:'09:00',local:'Comercial Almeida',endereco:'Av. Principal',servico:'Limpeza, reaperto e conferência dos módulos',equipe:'Equipe Técnica 03',tipo:'Preventiva',status:'Confirmado',prioridade:'Média'}];
 const relatorios=[{codigo:'RD-001',dia:'15/05/2026',cliente:'Mercado Central',atividade:'Correção de falha de comunicação no monitoramento SOLIS',resultado:'Comunicação restabelecida e sistema normalizado',responsavel:'Lucas',status:'Bem-sucedido',fotos:3,assinatura:'Coletada'},{codigo:'RD-002',dia:'15/05/2026',cliente:'Residencial Lima',atividade:'Limpeza de módulos e inspeção visual completa',resultado:'Geração estabilizada após o procedimento',responsavel:'Equipe Técnica 01',status:'Bem-sucedido',fotos:8,assinatura:'Coletada'},{codigo:'RD-003',dia:'14/05/2026',cliente:'Fazenda Nova Esperança',atividade:'Análise de queda de produção',resultado:'Necessária nova visita para troca de conector MC4',responsavel:'Equipe Técnica 02',status:'Acompanhar',fotos:5,assinatura:'Pendente'}];
 const clientes=[{nome:'Fazenda Oliveira',cidade:'Zona Rural',painel:'SOLARMAN',potencia:'18,4 kWp',status:'Com alerta'},{nome:'Mercado Central',cidade:'Centro',painel:'SOLIS',potencia:'12,0 kWp',status:'Normal'},{nome:'Residencial Souza',cidade:'Centro',painel:'GOODWE',potencia:'5,5 kWp',status:'Em análise'},{nome:'Comercial Almeida',cidade:'Av. Principal',painel:'RENAC',potencia:'22,0 kWp',status:'Acompanhar'}];
 const filtrados=useMemo(()=>alertas.filter(a=>(`${a.id} ${a.cliente} ${a.painel} ${a.inversor} ${a.situacao} ${a.status}`.toLowerCase().includes(busca.toLowerCase()))&&(filtro==='Todos'||a.status===filtro)),[busca,filtro]);
 const Button=({id,Icon,children})=><button className={aba===id?'nav active':'nav'} onClick={()=>setAba(id)}><Icon size={18}/>{children}</button>;
 return <main><header className="hero"><div className="brand"><img src={logo}/><div><span><Sun size={18}/> Gestão profissional de energia solar</span><h1>Sistema MF Elétrica Solar</h1><p>Controle completo de alertas, clientes, monitoramento, agenda técnica, relatórios, evidências e desempenho operacional.</p></div></div><div className="online"><ShieldCheck/><b>Operando</b><small>Monitoramento ativo</small></div></header>
 <nav className="tabs"><Button id="dashboard" Icon={LayoutDashboard}>Dashboard</Button><Button id="alertas" Icon={AlertTriangle}>Alertas</Button><Button id="agenda" Icon={CalendarDays}>Agenda</Button><Button id="relatorios" Icon={FileText}>Relatórios</Button><Button id="clientes" Icon={UsersRound}>Clientes</Button><Button id="paineis" Icon={Gauge}>Painéis</Button><Button id="checklist" Icon={ClipboardCheck}>Checklist</Button></nav>
 {aba==='dashboard'&&<section><div className="grid four"><Card title="Alertas pendentes" value={alertas.filter(a=>a.status!=='Resolvido').length} desc="Precisam de análise" Icon={AlertTriangle}/><Card title="Alertas resolvidos" value={alertas.filter(a=>a.status==='Resolvido').length} desc="Finalizados com sucesso" Icon={CheckCircle2}/><Card title="Serviços do dia" value="2" desc="Visitas programadas" Icon={CalendarDays}/><Card title="Tarefas concluídas" value="2" desc="Relatórios bem-sucedidos" Icon={Zap}/></div><div className="panel"><h2>Ocorrências recentes</h2>{alertas.map(a=><div className="row" key={a.id}><div><Status>{a.prioridade}</Status> <Status>{a.status}</Status><h3>{a.cliente}</h3><p>{a.situacao}</p></div><b>{a.painel}</b></div>)}</div></section>}
 {aba==='alertas'&&<section className="panel"><div className="toolbar"><div><h2>Central de Alertas</h2><p>Registre cliente, painel, inversor, ocorrência, prioridade e resolução.</p></div><div className="search"><Search size={18}/><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar alerta..."/><select value={filtro} onChange={e=>setFiltro(e.target.value)}><option>Todos</option><option>Pendente</option><option>Em análise</option><option>Acompanhar</option><option>Resolvido</option></select></div></div><div className="grid two">{filtrados.map(a=><article className="item" key={a.id}><div className="itemHead"><div><small>{a.id}</small><h3>{a.cliente}</h3></div><div><Status>{a.prioridade}</Status> <Status>{a.status}</Status></div></div><p><b>Painel:</b> {a.painel} • <b>Inversor:</b> {a.inversor}</p><p><b>Data:</b> {a.data} {a.horario} • <b>Contato:</b> {a.contato}</p><h4>{a.situacao}</h4><p>{a.obs}</p><footer>Responsável: <b>{a.responsavel}</b></footer></article>)}</div></section>}
 {aba==='agenda'&&<Cards title="Agenda Técnica" data={agenda} type="agenda" />}
 {aba==='relatorios'&&<Cards title="Relatórios do Dia" data={relatorios} type="relatorios" />}
 {aba==='clientes'&&<section className="panel"><h2>Cadastro de Clientes</h2><div className="grid four">{clientes.map(c=><article className="item" key={c.nome}><Home/><h3>{c.nome}</h3><p>{c.cidade}</p><p><b>Painel:</b> {c.painel}</p><p><b>Potência:</b> {c.potencia}</p><Status>{c.status}</Status></article>)}</div></section>}
 {aba==='paineis'&&<section className="panel"><h2>Painéis de Monitoramento</h2><div className="grid three">{paineis.map(p=><article className="item" key={p}><Gauge/><h3>{p}</h3><p>Disponível para alertas, clientes, relatórios e acompanhamento técnico.</p><Status>Normal</Status></article>)}</div></section>}
 {aba==='checklist'&&<section className="panel"><h2>Checklist Técnico</h2>{['Conferir geração atual e histórico do cliente','Verificar comunicação do inversor com internet','Inspecionar módulos, conectores e cabos aparentes','Registrar fotos antes e depois do serviço','Atualizar status do alerta','Adicionar relatório diário com resultado final'].map((x,i)=><div className="check" key={x}><b>{i+1}</b>{x}</div>)}</section>}
 <footer><b>MF Elétrica Solar</b><span><Wrench size={18}/> Organização, rapidez e controle operacional</span></footer></main>}
function Cards({title,data,type}){return <section className="panel"><h2>{title}</h2><div className="grid three">{data.map((x,i)=><article className="item" key={i}>{type==='agenda'?<><Clock/><h3>{x.local}</h3><p><b>{x.data}</b> às {x.horario}</p><p><MapPin size={14}/> {x.endereco}</p><p>{x.servico}</p><Status>{x.status}</Status> <Status>{x.prioridade}</Status><footer>{x.equipe} • {x.tipo}</footer></>:<><Camera/><small>{x.codigo} • {x.dia}</small><h3>{x.cliente}</h3><p>{x.atividade}</p><p><b>Resultado:</b> {x.resultado}</p><Status>{x.status}</Status><footer>{x.responsavel} • {x.fotos} fotos • Assinatura: {x.assinatura}</footer></>}</article>)}</div></section>}

createRoot(document.getElementById('root')).render(<App />);
